# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/service/service.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "courier.ListFeedsRequest" do
  end
  add_message "courier.ListUserFeedsRequest" do
    optional :user_id, :int32, 1
  end
  add_message "courier.RegisterFeedRequest" do
    optional :user_id, :int32, 1
    optional :url, :string, 2
  end
  add_message "courier.RefreshFeedRequest" do
    optional :feed_id, :int32, 1
  end
  add_message "courier.PingRequest" do
    optional :title, :string, 1
    optional :url, :string, 2
  end
  add_message "courier.Feed" do
    optional :id, :int32, 1
    optional :url, :string, 2
    optional :created_at, :message, 3, "google.protobuf.Timestamp"
    optional :updated_at, :message, 4, "google.protobuf.Timestamp"
    optional :refreshed_at, :message, 5, "google.protobuf.Timestamp"
    optional :title, :string, 6
    optional :home_page_url, :string, 7
  end
  add_message "courier.FeedList" do
    repeated :feeds, :message, 1, "courier.Feed"
  end
  add_message "courier.JobStatus" do
    optional :status, :string, 1
    optional :job_id, :string, 2
  end
end

module Courier
  ListFeedsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.ListFeedsRequest").msgclass
  ListUserFeedsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.ListUserFeedsRequest").msgclass
  RegisterFeedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.RegisterFeedRequest").msgclass
  RefreshFeedRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.RefreshFeedRequest").msgclass
  PingRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.PingRequest").msgclass
  Feed = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.Feed").msgclass
  FeedList = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.FeedList").msgclass
  JobStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("courier.JobStatus").msgclass
end
