# Code generated by protoc-gen-twirp_ruby 1.0.0, DO NOT EDIT.
require 'twirp'
require_relative 'service_pb.rb'

module Courier
  class FeedsService < Twirp::Service
    package 'courier'
    service 'Feeds'
    rpc :GetFeeds, ListFeedsRequest, FeedList, :ruby_method => :get_feeds
    rpc :GetUserFeeds, ListUserFeedsRequest, FeedList, :ruby_method => :get_user_feeds
    rpc :RegisterFeed, RegisterFeedRequest, Feed, :ruby_method => :register_feed
    rpc :RefreshFeed, RefreshFeedRequest, JobStatus, :ruby_method => :refresh_feed
    rpc :Ping, PingRequest, FeedList, :ruby_method => :ping
  end

  class FeedsClient < Twirp::Client
    client_for FeedsService
  end
end
