sudo: false
language: ruby
rvm:
- 2.5.1
cache: bundler
before_install:
- openssl aes-256-cbc -K $encrypted_e24b690838e6_key -iv $encrypted_e24b690838e6_iv
  -in service-account.json.enc -out service-account.json -d
- gem install bundler -v 1.16.1
deploy:
  provider: gae
  project: stable-reactor-209402
